core/urls.py
from django.urls import path,re_path
from core import views
from django.conf.urls import handler404



urlpatterns = [
    path("", views.index , name= 'index'),
    path("dashboard/", views.dashboard, name = 'dashboard'),
    path("edit_profile/", views.edit_profile, name = 'edit_profile'),
    path("my_address/", views.my_address, name = 'my_address'),
    path("addAddress/", views.addAddress, name = 'addAddress'),
    path("editAddress/<int:id>/", views.editAddress, name = 'editAddress'),
    path('deleteAddress/<int:id>/', views.deleteAddress, name='deleteAddress'),
    path("change_password/", views.change_password, name = 'change_password'),
    path('deleteCheckoutAddress/<int:id>/', views.deleteCheckoutAddress, name='deleteCheckoutAddress'),
    path('AddCheckoutAddress/', views.AddCheckoutAddress, name='AddCheckoutAddress'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('my_wallet/', views.my_wallet, name='my_wallet'),
    path('my_wishlist/', views.my_wishlist, name='my_wishlist'),
    path('order_details/<int:order_id>', views.order_details, name='order_details'),
    path("invoice/<int:order_id>", views.generate_invoice_pdf,name='invoice'),
    path("contact_us",views.contact,name= 'contact'),

]

palettepassion/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("store/", include("store.urls")),
    path("adminpanel/", include("adminpanel.urls")),
    path("cart/", include("carts.urls")),
    path("order/", include("order.urls")),


]

if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

handler404 = 'core.views.error'

core/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.mail import send_mail
from accounts.models import *
from store.models import *

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.CharField(max_length=250)
    subject = models.CharField(max_length = 300)
    message = models.TextField()
    
@receiver(post_save, sender=Contact)
def _post_save_receiver(sender, instance, **kwargs):
    subject = 'This is contact us Mails from Your Users '
    message = f'{instance.message}'
    from_email = instance.email 
    recipient_email =  'fathimagm0@gmail.com'
    recipient_list = [recipient_email]

    send_mail(subject, message, from_email, recipient_list, fail_silently=False)

class RecentViewedProduct(models.Model):
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE , related_name='recent_viewed_product')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        # Get the total count of rows in the table
        total_rows = RecentViewedProduct.objects.filter(user=self.user).count()

        # If the user already has 10 rows, delete the oldest row before adding the new one
        if total_rows >= 7:
            oldest_row = RecentViewedProduct.objects.filter(user=self.user).order_by('updated_at').first()
            oldest_row.delete()

        # Call the parent class's save method to save the new row
        super(RecentViewedProduct, self).save(*args, **kwargs)
        
        

    def __str__(self):
        return self.user.first_name+" "+self.product.product_name()

order/models.py
from django.db import models
from accounts.models import *
from store.models import *
from django_countries.fields import CountryField
from django.core.validators import MinValueValidator,MaxValueValidator

# Create your models here.

class Address(models.Model):
    user          = models.ForeignKey(Account,on_delete=models.CASCADE)
    first_name    = models.CharField(max_length = 50)
    last_name     = models.CharField(max_length = 50)
    phone         = models.CharField(max_length = 15)
    email         = models.EmailField(max_length = 50)
    address_line1 = models.CharField(max_length=50)
    address_line2 = models.CharField(max_length=50,null=True)
    state         = models.CharField(max_length=50)
    # country_choices = list(CountryField().get_choices()) + [('', 'Select Country')]
    # country        = models.CharField(max_length=200, null=True, choices=country_choices)
    country       = CountryField(max_length = 200)    
    city          = models.CharField(max_length=50,blank=True)
    zipcode       = models.CharField(max_length=20)
    order_note    = models.CharField(max_length=100, blank=True)
    
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def address(self):
        return f"{self.address_line1} {self.address_line2}"

    def __str__(self):
        return self.first_name
    
class Payment(models.Model):
    user           = models.ForeignKey(Account,on_delete=models.CASCADE)
    payment_id     = models.CharField(max_length=100)
    order_id       = models.CharField(max_length=100,blank=True,default='empty')
    payment_method = models.CharField(max_length=100)
    amount_paid    = models.FloatField(default=0)
    status         = models.CharField(max_length=100)
    created_at     = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.payment_id
    

class Order(models.Model):
    STATUS = (
        ('Order_Confirmed', 'Order Confirmed'),
        ('Shipped',"Shipped"),
        ('Out_for_delivery',"Out for delivery"),
        ('Delivered', 'Delivered'),
        ('Cancelled','Cancelled'),
        ('Returned','Returned'),
    )
    user           = models.ForeignKey(Account,on_delete=models.SET_NULL,null=True)
    payment        = models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    order_number   = models.CharField(max_length=20)
    first_name     = models.CharField(max_length=50)
    last_name      = models.CharField(max_length=50)
    phone          = models.CharField(max_length=15)
    email          = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50,blank=True)
    country        = CountryField(null = True)
    state          = models.CharField(max_length=50)
    city           = models.CharField(max_length=50)
    order_note     = models.CharField(max_length=100,blank=True)
    zipcode        = models.CharField(max_length=20,default=1)
    order_total    = models.FloatField()
    order_discount = models.FloatField(default=0)
    tax            = models.FloatField()
    status         = models.CharField(max_length=50,choices=STATUS,default='Order Confirmed')
    ip             = models.CharField(blank=True,max_length=20)
    is_ordered     = models.BooleanField(default=False)
    is_returned    = models.BooleanField(default=False)
    return_reason  = models.CharField(max_length=50, blank=True)
    created_at     = models.DateField(auto_now_add=True)
    updated_at     = models.DateField(auto_now=True)
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name 
    
class OrderProduct(models.Model):
    order         = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='user_order_page')
    payment       = models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    user          = models.ForeignKey(Account,on_delete=models.CASCADE)
    product       = models.ForeignKey(Product,on_delete=models.CASCADE)
    variations    = models.ForeignKey(Variation,on_delete=models.CASCADE,default=0)
    quantity      = models.IntegerField()
    product_price = models.FloatField()
    ordered       = models.BooleanField(default=False)
    created_at    = models.DateField(auto_now_add=True)
    updated_at    = models.DateField(auto_now=True)

    def __str__(self):
        return self.product.product_name
    def sub_total(self):
        return self.product.get_product_price_by_size_id(self.variations.pk) * self.quantity
    

class Coupon(models.Model):
    code       = models.CharField(max_length= 50, unique= True)
    discount   = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(30)])
    min_value  = models.IntegerField(validators=[MinValueValidator(0)])
    valid_from = models.DateTimeField(auto_now_add= True)
    valid_to   = models.DateField()
    active     = models.BooleanField(default= False)

    def __str__(self):
        return self.code
    
class UserCoupon(models.Model):
    user      = models.ForeignKey(Account,on_delete=models.CASCADE,null=True)
    coupon    = models.ForeignKey(Coupon,on_delete=models.CASCADE,null=True)
    order     = models.ForeignKey(Order,on_delete=models.CASCADE,null=True,related_name='order_coupon')
    used      = models.BooleanField(default= False)

    def __str__(self):
        return str(self.id)

templates/userside/userprofile/add_address.html
{% extends 'userside/partial/base.html' %}

{% load static %}

{% block content %}
<!-- Body Start -->
<div class="wrapper">
    <div class="gambo-Breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'dashboard' %}">User
                                    Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'addAddress' %}">Add Address</a></li>
                            {% include 'userside/includes/alert.html' %}
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    
    <div class="mb-5">
        <div class="container">
            <div class="row">
                {% include 'userside/partial/dashboard_sidebar.html' %}

                <div class="col-lg-9 col-md-8">
                    <div class="dashboard-right">
                        <div class="row">

                            <div class="col-lg-12 col-md-12">
                                <div class="pdpt-bg" style="background:  rgba(0, 0, 0, 0.782);">
                                    <div class="pdpt-title">
                                        <h4 style="color: aliceblue;">Add New Address</h4>
                                    </div>
                                </div>
                                <article class="card">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <form action="{% url 'addAddress' %}" method="POST"
                                                    enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="form-row">
                                                        <div class="form-group col-md-6">
                                                            <label>First Name</label>
                                                            {{form.first_name}}
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label>Last Name</label>
                                                            {{form.last_name}}
                                                        </div>

                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col-md-6">
                                                            <label>Email</label>
                                                            {% comment %} {{form.email}} {% endcomment %}
                                                            <input type="email" name="email" maxlength="50"
                                                                class="form-control" onkeyup="validateAddAddressEmail()"
                                                                id="id_email">
                                                            <span id="email-error" class='change'></span>
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label>Phone Number</label>
                                                            {% comment %} {{form.phone}} {% endcomment %}
                                                            <input type="text" name="phone" maxlength="15"
                                                                class="form-control"
                                                                onkeyup="validateAddAddressMobilenumber()"
                                                                id="id_phone">
                                                            <span id="mobilenumber-error" class='change'></span>
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label>Address Line 1</label>
                                                            {{form.address_line1}}
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label>Address Line 2</label>
                                                            {{form.address_line2}}
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label>City</label>
                                                            {{form.city}}
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label>Zip Code</label>
                                                            {{form.zipcode}}
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label>Country</label>
                                                            {{form.country}}
                                                        </div>
                                                        
                                                        <div class="form-group col-md-6">
                                                            <label>State</label>
                                                            {{form.state}}
                                                        </div>

                                                    </div>
                                                    <input type="submit" name="" id="" value="Save"
                                                        onclick="return validateAddAddresForm()" class="btn btn-dark">
                                                    <span id="submit-error" class="mt-2"></span>

                                                </form>

                                            </div>
                                        </div> <!-- row.// -->
                                    </div> <!-- card-body .// -->


                                    <!-- table-responsive .end// -->
                                </article> <!-- order-group.// -->
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Body End -->

    {% endblock content %}

templates/userside/userprofile/edit_address.html
{% extends 'userside/partial/base.html' %}

{% load static %}


{% block content %}
<!-- Body Start -->
<div class="wrapper">
    <div class="gambo-Breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'dashboard' %}">User
                                    Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="">Edit Address</a></li>
                            
                                    {% include 'userside/includes/alert.html' %}
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
        
    <div class="mb-5">
        <div class="container">
            <div class="row">
                {% include 'userside/partial/dashboard_sidebar.html' %}

                <div class="col-lg-9 col-md-8">
                    <div class="dashboard-right">
                        <div class="row">
                            
                            <div class="col-lg-12 col-md-12">
                                <div class="pdpt-bg" style="background:  rgba(0, 0, 0, 0.782);">
                                    <div class="pdpt-title">
                                        <h4 style="color: aliceblue;">Edit Address</h4>
                                    </div>
                              </div> 
                            <article class="card">
                            <div class="card-body">
                              <div class="row"> 
                              <div class="col-md-12">
                                <form action="" method="POST" enctype="multipart/form-data" >
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label >First Name</label>
                                           
                                           {{form.first_name}} 
                                           
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label >Last Name</label>
                                            {{form.last_name}}
                                            
                                        </div>
                    
                                    </div>
                                    <div class="form-row">
                                      <div class="form-group col-md-6">
                                          <label >Email</label>
                                          <input type="email" name="email" value="{{form.email.value}}" maxlength="50" onkeyup="validateAddAddressEmail()" class="form-control" id="id_email">
                                              <span id="email-error"class='change'></span>
                                          {% comment %} {{form.email}} {% endcomment %}
                  
                                         
                                      </div>
                                      <div class="form-group col-md-6">
                                            <label >Phone Number</label>
                                            <input type="text" name="phone" value="{{form.phone.value}}" maxlength="15" onkeyup="validateAddAddressMobilenumber()" class="form-control"  id="id_phone">
                                            <span id="mobilenumber-error"class='change'></span>
                                            {% comment %} {{form.phone}} {% endcomment %}
                                            
                                      </div>
                                      <div class="form-group col-md-6">
                                        <label >Address Line 1</label>
                                        {{form.address_line1}}
                                       
                                      </div>
                                      
                                      <div class="form-group col-md-6">
                                        <label >Address Line 2</label>
                                        {{form.address_line2}}
                                       
                                      </div>
                                      <div class="form-group col-md-6">
                                        <label >City</label>
                                        {{form.city}}
                                       
                                      </div>
                                      <div class="form-group col-md-6">
                                        <label >State</label>
                                        {{form.state}}
                                       
                                      </div>
                                      <div class="form-group col-md-6">
                                        <label >Zip Code</label>
                                        {{form.zipcode}}
                                       
                                      </div>
                                      <div class="form-group col-md-6">
                                        <label >country</label>
                                        {{form.country}}
                                       
                                      </div>
                                     
                                           
                                    </div>
                                    <input type="submit" name="" id="" value="Save" onclick="return validateAddAddresForm()" class="btn btn-dark">
                                     <span id="submit-error" class="mt-2"></span>
                    
                                   </form>
                               
                              </div>
                              </div> <!-- row.// -->
                            </div> <!-- card-body .// -->
                        
                            
                             <!-- table-responsive .end// -->
                            </article> <!-- order-group.// --> 
                        </div>

                    </div>
                </div>
            </div>	
        </div>	
    </div>	
</div>
<!-- Body End -->

{% endblock content %}

templates/userside/userprofile/edit_profile.html
{% extends 'userside/partial/base.html' %}

{% load static %}


{% block content %}
<!-- Body Start -->
<div class="wrapper">
  <div class="gambo-Breadcrumb">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'dashboard' %}">User
                  Dashboard</a></li>
              <li class="breadcrumb-item"><a href="{% url 'edit_profile' %}">Edit Profile</a></li>

              {% include 'userside/includes/alert.html' %}
              {% include 'userside/includes/form.html' %}



            </ol>
          </nav>

        </div>
      </div>
    </div>
  </div>

  <div class="mb-5">
    <div class="container">
      <div class="row">

        {% include 'userside/partial/dashboard_sidebar.html' %}

        <div class="col-lg-6 col-md-12">
          <div class="pdpt-bg">
            <div class="pdpt-title" style="background-color:  black ">
              <h4 style="color: aliceblue;">Edit Your Profile</h4>
            </div>
            <!-- <main class="col-md-9"> -->
            <article class="card">
              <!-- <header class="card-header">
                                <strong class="d-inline-block mr-3">Edit your profile</strong>
                              </header> -->
              <div class="card-body">
                <div class="text-right">
                  {% if userprofile.profile_picture.url != '' %}
                  <img src="{{userprofile.profile_picture.url}}" alt="profile picture" width="100" height="100"
                    style="border-radius:60px;">
                  {%endif%}
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <form action="{% url 'edit_profile' %}" method="POST" enctype="multipart/form-data">

                      {% csrf_token %}

                      {% if user_form.errors %}
                      <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {% for field, error_list in user_form.errors.items %}
                        {% for error in error_list %}
                        {{ error }}
                        {% endfor %}
                        {% endfor %}
                      </div>
                      {% endif %}

                      <div class="form-row">
                        <div class="form-group col-md-6">
                          <label>First name</label>
                          {{user_form.first_name}}

                        </div>
                        <div class="form-group col-md-6">
                          <label>Last name</label>
                          {{user_form.last_name}}

                        </div>
                        <div class="form-group col-md-6">
                          <label>Phone number</label>

                          {% comment %} {{user_form.phone}} {% endcomment %}
                          <input type="text" name="phone_number" value="{{user.phone_number}}"
                            onkeyup="validateEditProfMobilenumber()" class="form-control" id="id_phone">
                          <span id="mobilenumber-error" class='change'></span>

                        </div>
                        <div class="form-group col-md-6">
                          <label>Profile pitcure</label>
                          {{profile_form.profile_picture}}

                        </div>
                      </div>
                      <div class="form-group">
                        <label>email</label>
                        {% comment %} {{user_form.email}} {% endcomment %}
                        <input type="email" name="email" value="{{user.email}}" maxlength="254"
                          onkeyup="validateEditProfEmail()" class="form-control" id="id_email">
                        <span id="email-error" class='change'></span>


                      </div>
                      <div class="form-group">
                        <label>Address Line 1</label>
                        {{profile_form.address_line_1}}


                      </div>
                      <div class="form-group">
                        <label>Address Line 2</label>

                        {{profile_form.address_line_2}}


                      </div>
                      <div class="form-row">
                        <div class="form-group col-md-4">
                          <label>City</label>
                          {{profile_form.city}}


                        </div>
                        <div class="form-group col-md-4">
                          <label>State</label>
                          {{profile_form.state}}

                        </div>
                        <div class="form-group col-md-4">
                          <label>country</label>
                          {{profile_form.country}}

                        </div>
                      </div>
                      <input type="submit" value="save" onclick="return validateEditProfForm()"
                        class="next-btn16 hover-btn mt-3">
                      <span id="submit-error" class="mt-5"></span>

                    </form>
                  </div>
                </div>
              </div>
            </article>
            <!-- </main> -->
          </div>
        </div>
      </div>
    </div>
  </div>


  {% endblock content %}

templates/userside/userprofile/my_wallet.html
{% extends 'userside/partial/base.html' %}

{% load static %}


{% block content %}
<!-- Body Start -->
<div class="wrapper">
    <div class="gambo-Breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'dashboard' %}">User
                                    Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'my_wallet' %}">My Wallet</a></li>
                            {% include 'userside/includes/alert.html' %}
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    
    <div class="">
        <div class="container">
            <div class="row">
                {% include 'userside/partial/dashboard_sidebar.html' %}
                <div class="col-lg-9 col-md-8">
                    <div class="dashboard-right">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="main-title-tab">
                                    <h4><i class="uil uil-wallet"></i>My Wallet</h4>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <div class="pdpt-bg">
                                    <div class="reward-body-dtt">
                                        <div class="reward-img-icon">
                                            <img src="{% static 'images/money.svg' %}" alt="">
                                        </div>
                                        <span class="rewrd-title">My Balance</span>
                                        <h4 class="cashbk-price">${{userprofile.wallet}}</h4>
                                        <span class="date-reward"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Body End -->

    {% endblock content %}